# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths: git RE3CON/Quansheng_UV-K5_Firmware/uvmod_kitchen_v3.00.15/

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     
    - name: make
      working-directory: ./uvmod_kitchen_v3.00.15
      run: build.bat 
